const Data = [
  {
    id: 1,
    patient: "Yavuz Selim",
    appointment: "Dec 12th at 2:30pm",
    isCompleted: false,
    doctor: "Prof. Akari Yoshino",
    reason: "Check-up",
  },
  {
    id: 2,
    patient: "Mihrimah Sultan",
    appointment: "Dec 13th at 1:30pm",
    isCompleted: true,
    doctor: "Dr. Alena Mangold",
    reason: "Emergency",
  },
  {
    id: 3,
    patient: "Fatih Mehmet",
    appointment: "Dec 14th at 3:00pm",
    isCompleted: false,
    doctor: "Dr. Lian Kurzmann",
    reason: "Follow-up",
  },
  {
    id: 4,
    patient: "İpek Bilir",
    appointment: "Dec 12th at 2:30pm",
    isCompleted: false,
    doctor: "Prof. Dr. Benjamin Daley",
    reason: "Check-up",
  },
  {
    id: 5,
    patient: "Haluk Yilmaz",
    appointment: "Dec 13th at 1:30pm",
    isCompleted: true,
    doctor: "MD. Eva Manz",
    reason: "Routine",
  },
  {
    id: 6,
    patient: "Ayşe Güler",
    appointment: "Dec 14th at 3:00pm",
    isCompleted: false,
    doctor: "Prof. Dr. Theodor Jackson",
    reason: "Walkin",
  },
  {
    id: 7,
    patient: "Ayşe Güler",
    appointment: "Dec 14th at 3:00pm",
    isCompleted: false,
    doctor: "Dr. Nari Chung",
    reason: "Emergency",
  },
  {
    id: 8,
    patient: "Ayşe Güler",
    appointment: "Dec 14th at 3:00pm",
    isCompleted: false,
    doctor: "Ass. Prof. Dr. Wulf Gabler",
    reason: "Routine",
  },
];
export default Data;
